In [2]:
#Practicing Math Library
import math

In [4]:
A=16
print(math.sqrt(A))

4.0


In [7]:
B=3.14
from math import sqrt, sin
print(sqrt(A))
print(sin(B))

4.0
0.0015926529164868282


In [14]:
#Practicing NumPy Library
import numpy as np

In [16]:
np_sqrt = np.sqrt([2,4,9,16])
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

In [20]:
from numpy import pi
np.cos(0)

1.0

In [22]:
np.sin(pi/2)

1.0

In [24]:
np.cos(pi)

-1.0

In [27]:
np.floor([1.5,1.6,2.7,3.3,1.1, -0.3,-1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [29]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

In [34]:
#shape Manipulation
new_cyclist_trials=np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [36]:
new_cyclist_trials.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [38]:
a = new_cyclist_trials

In [40]:
a.resize(2,6)

In [42]:
a

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [44]:
np.hsplit(a,2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [46]:
a_1 = np.array([10,15,17,26,13,19])

In [49]:
a_2 = np.array([12,11,21,24,14,23])

In [54]:
np.hstack((a_1,a_2))

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [58]:
type(a_1)
print(a_1)

[10 15 17 26 13 19]


In [60]:
# array with zeros
array_0 = np.zeros((5,5))
array_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
# array with ones
array_0 = np.ones((5,5))
array_0

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
# array with empty / assign randoms
array_emp = np.empty((4,3))
array_emp

array([[1.41047864e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.14587773e-312, 3.93208315e-061],
       [4.54604047e+174, 3.88714376e-057, 1.91830604e-076],
       [2.51310882e+180, 9.95811480e-047, 9.20231229e+169]])

In [79]:
# arange method
np_arange = np.arange(15)
print(np_arange)
np_arange.reshape(3,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [81]:
#linspace for Linearly (equal) spaced data elements
np_linspce = np.linspace(1,6,5)
print (np_linspce)

[1.   2.25 3.5  4.75 6.  ]


In [82]:
#Three dimensional array 
ThreeD_array = np.arange(27).reshape(3,3,3)
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
